import pandas as pd
import json

df=pd.read_excel('/home/sohansagar/Documents/automate/240_2022-03-2616-06-52.187083.xlsx',sheet_name='Sheet')
SJT_Cash=df[(df["Mode"]=="issuance") & (df["Type"]=="SJT") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
SJT_Card=df[(df["Mode"]=="issuance") & (df["Type"]=="SJT") & ((df["Payment"]=="Card")) ]["Amount"].sum()
SJT_UPI=df[(df["Mode"]=="issuance") & (df["Type"]=="SJT") & ((df["Payment"]=="UPI")) ]["Amount"].sum()
SJT_Cash_count=df[(df["Mode"]=="issuance") & (df["Type"]=="SJT") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
SJT_Card_count=df[(df["Mode"]=="issuance") & (df["Type"]=="SJT") & ((df["Payment"]=="Card")) ]["Qantity"].sum()
SJT_UPI_count=df[(df["Mode"]=="issuance") & (df["Type"]=="SJT") & ((df["Payment"]=="UPI")) ]["Qantity"].sum()
RJT_Cash=df[(df["Mode"]=="issuance") & (df["Type"]=="RJT") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
RJT_Card=df[(df["Mode"]=="issuance") & (df["Type"]=="RJT") & ((df["Payment"]=="Card")) ]["Amount"].sum()
RJT_UPI=df[(df["Mode"]=="issuance") & (df["Type"]=="RJT") & ((df["Payment"]=="UPI")) ]["Amount"].sum()
RJT_Cash_count=df[(df["Mode"]=="issuance") & (df["Type"]=="RJT") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
RJT_Card_count=df[(df["Mode"]=="issuance") & (df["Type"]=="RJT") & ((df["Payment"]=="Card")) ]["Qantity"].sum()
RJT_UPI_count=df[(df["Mode"]=="issuance") & (df["Type"]=="TJT") & ((df["Payment"]=="UPI")) ]["Qantity"].sum()
GRP_Cash=df[(df["Mode"]=="issuance") & (df["Type"]=="GRP") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
GRP_Card=df[(df["Mode"]=="issuance") & (df["Type"]=="GRP") & ((df["Payment"]=="Card")) ]["Amount"].sum()
GRP_UPI=df[(df["Mode"]=="issuance") & (df["Type"]=="GRP") & ((df["Payment"]=="UPI")) ]["Amount"].sum()
GRP_Cash_count=df[(df["Mode"]=="issuance") & (df["Type"]=="GRP") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
GRP_Card_count=df[(df["Mode"]=="issuance") & (df["Type"]=="GRP") & ((df["Payment"]=="Card")) ]["Qantity"].sum()
GRP_UPI_count=df[(df["Mode"]=="issuance") & (df["Type"]=="GRP") & ((df["Payment"]=="UPI")) ]["Qantity"].sum()
print(SJT_Cash_count,SJT_Cash,SJT_Card_count, SJT_Card ,SJT_UPI_count, SJT_UPI)
print(RJT_Cash_count,RJT_Cash,RJT_Card_count, RJT_Card ,RJT_UPI_count, RJT_UPI)
print(GRP_Cash_count,GRP_Cash,GRP_Card_count, GRP_Card ,GRP_UPI_count, GRP_UPI)
issuance_count= SJT_Cash_count + SJT_Card_count +SJT_UPI_count + RJT_Cash_count +RJT_Card_count +RJT_UPI_count + GRP_Cash_count +GRP_Card_count +GRP_UPI_count
issuance_amount=SJT_Cash+SJT_Card+SJT_UPI+RJT_Cash+RJT_Card+RJT_UPI+GRP_Cash+GRP_Card +GRP_UPI
print(f'issuance count is {issuance_count} amounting Rs {issuance_amount}')
SJT_replacement= df[(df["Mode"]=="Replacement") & (df["Type"]==" SJT") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
SJT_relacement_count=df[(df["Mode"]=="Replacement") & (df["Type"]==" SJT") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
RJT_replacement=df[(df["Mode"]=="Replacement") & (df["Type"]==" RJT") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
RJT_replacement_count=df[(df["Mode"]=="Replacement") & (df["Type"]==" RJT") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
GRP_replacement=df[(df["Mode"]=="Replacement") & (df["Type"]==" GRP") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
GRP_replacement_count=df[(df["Mode"]=="Replacement") & (df["Type"]==" GRP") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
replace_count=SJT_relacement_count+RJT_replacement_count+GRP_replacement_count
replace_amount=SJT_replacement+RJT_replacement+GRP_replacement
print(f'Replace count is {replace_count} and replace amount is  {replace_amount}')
Analysis_count =df[df["Mode"]=="Analysis" ]["Qantity"].sum()
Analysis_amount =df[df["Mode"]=="Analysis" ]["Amount"].sum()
print(f"Analysis count is {Analysis_count} and analysis amount is {Analysis_amount}")
SJT_Refund= df[(df["Mode"]=="Refund") & (df["Type"]==" SJT") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
SJT_Refund_count=df[(df["Mode"]=="Refund") & (df["Type"]==" SJT") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
RJT_Refund=df[(df["Mode"]=="Refund") & (df["Type"]==" RJT") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
RJT_Refund_count=df[(df["Mode"]=="Refund") & (df["Type"]==" RJT") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
refund_amt=SJT_Refund+RJT_Refund
refund_count=SJT_Refund_count+RJT_Refund_count
print(f'Refund count is {refund_count} and Refund amount is {refund_amt}')

SJT_Cash_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="SJT") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
SJT_Card_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="SJT") & ((df["Payment"]=="Card")) ]["Amount"].sum()
SJT_UPI_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="SJT") & ((df["Payment"]=="UPI")) ]["Amount"].sum()
SJT_Cash_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="SJT") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
SJT_Card_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="SJT") & ((df["Payment"]=="Card")) ]["Qantity"].sum()
SJT_UPI_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="SJT") & ((df["Payment"]=="UPI")) ]["Qantity"].sum()
RJT_Cash_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="RJT") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
RJT_Card_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="RJT") & ((df["Payment"]=="Card")) ]["Amount"].sum()
RJT_UPI_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="RJT") & ((df["Payment"]=="UPI")) ]["Amount"].sum()
RJT_Cash_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="RJT") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
RJT_Card_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="RJT") & ((df["Payment"]=="Card")) ]["Qantity"].sum()
RJT_UPI_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="TJT") & ((df["Payment"]=="UPI")) ]["Qantity"].sum()
GRP_Cash_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="GRP") & ((df["Payment"]=="Cash")) ]["Amount"].sum()
GRP_Card_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="GRP") & ((df["Payment"]=="Card")) ]["Amount"].sum()
GRP_UPI_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="GRP") & ((df["Payment"]=="UPI")) ]["Amount"].sum()
GRP_Cash_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="GRP") & ((df["Payment"]=="Cash")) ]["Qantity"].sum()
GRP_Card_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="GRP") & ((df["Payment"]=="Card")) ]["Qantity"].sum()
GRP_UPI_count_Cancelation=df[(df["Mode"]=="Cancelation") & (df["Type"]=="GRP") & ((df["Payment"]=="UPI")) ]["Qantity"].sum()

Cancelationcount= SJT_Cash_count_Cancelation + SJT_Card_count_Cancelation +SJT_UPI_count_Cancelation + RJT_Cash_count_Cancelation +RJT_Card_count_Cancelation +RJT_UPI_count_Cancelation + GRP_Cash_count_Cancelation +GRP_Card_count_Cancelation +GRP_UPI_count_Cancelation
Cancelationamount=SJT_Cash_Cancelation+SJT_Card_Cancelation+SJT_UPI_Cancelation+RJT_Cash_Cancelation+RJT_Card_Cancelation+RJT_UPI_Cancelation+GRP_Cash_Cancelation+GRP_Card_Cancelation +GRP_UPI_Cancelation
print(f'Cancelation count is {Cancelationcount} and cancelation  amount is {Cancelationamount}')
FE_count =df[df["Mode"]=="FE" ]["Qantity"].sum()
FE_amount =df[df["Mode"]=="FE" ]["Amount"].sum()
print(f'free exit count is {FE_count} and free exit amount is {FE_amount}')
PE_count =df[df["Mode"]=="PE" ]["Qantity"].sum()
PE_amount =df[df["Mode"]=="PE" ]["Amount"].sum()
print(f'Paid exit count is{PE_count} and paid exit amount is {PE_amount}')
